/* Generated by Snowball 2.0.0 - https://snowballstem.org/ */

#include "header.h"

#ifdef __cplusplus
extern "C" {
#endif
extern int czech_UTF_8_stem(struct SN_env * z);
#ifdef __cplusplus
}
#endif
static int r_do_aggressive(struct SN_env * z);
static int r_do_deriv_single(struct SN_env * z);
static int r_do_derivational(struct SN_env * z);
static int r_do_augmentative(struct SN_env * z);
static int r_do_diminutive(struct SN_env * z);
static int r_do_comparative(struct SN_env * z);
static int r_do_case(struct SN_env * z);
static int r_do_possessive(struct SN_env * z);
static int r_mark_regions(struct SN_env * z);
static int r_palatalise(struct SN_env * z);
static int r_R1(struct SN_env * z);
static int r_RV(struct SN_env * z);
#ifdef __cplusplus
extern "C" {
#endif


extern struct SN_env * czech_UTF_8_create_env(void);
extern void czech_UTF_8_close_env(struct SN_env * z);


#ifdef __cplusplus
}
#endif
static const symbol s_0_0[2] = { 'c', 'e' };
static const symbol s_0_1[2] = { 'z', 'e' };
static const symbol s_0_2[3] = { 0xC2, 0xBE, 'e' };
static const symbol s_0_3[2] = { 'c', 'i' };
static const symbol s_0_4[4] = { 0xC3, 0xA8, 't', 'i' };
static const symbol s_0_5[4] = { 0xC2, 0xB9, 't', 'i' };
static const symbol s_0_6[2] = { 'z', 'i' };
static const symbol s_0_7[3] = { 0xC3, 0xA8, 'i' };
static const symbol s_0_8[3] = { 0xC2, 0xBE, 'i' };
static const symbol s_0_9[2] = { 0xC3, 0xA8 };
static const symbol s_0_10[5] = { 0xC3, 0xA8, 't', 0xC3, 0xA9 };
static const symbol s_0_11[5] = { 0xC2, 0xB9, 't', 0xC3, 0xA9 };
static const symbol s_0_12[5] = { 0xC3, 0xA8, 't', 0xC3, 0xAC };
static const symbol s_0_13[5] = { 0xC2, 0xB9, 't', 0xC3, 0xAC };

static const struct among a_0[14] =
{
{ 2, s_0_0, -1, 1, 0},
{ 2, s_0_1, -1, 2, 0},
{ 3, s_0_2, -1, 2, 0},
{ 2, s_0_3, -1, 1, 0},
{ 4, s_0_4, -1, 3, 0},
{ 4, s_0_5, -1, 4, 0},
{ 2, s_0_6, -1, 2, 0},
{ 3, s_0_7, -1, 1, 0},
{ 3, s_0_8, -1, 2, 0},
{ 2, s_0_9, -1, 1, 0},
{ 5, s_0_10, -1, 3, 0},
{ 5, s_0_11, -1, 4, 0},
{ 5, s_0_12, -1, 3, 0},
{ 5, s_0_13, -1, 4, 0}
};

static const symbol s_1_0[2] = { 'i', 'n' };
static const symbol s_1_1[2] = { 'o', 'v' };
static const symbol s_1_2[3] = { 0xC3, 0xB9, 'v' };

static const struct among a_1[3] =
{
{ 2, s_1_0, -1, 2, 0},
{ 2, s_1_1, -1, 1, 0},
{ 3, s_1_2, -1, 1, 0}
};

static const symbol s_2_0[1] = { 'a' };
static const symbol s_2_1[3] = { 'a', 'm', 'a' };
static const symbol s_2_2[3] = { 'a', 't', 'a' };
static const symbol s_2_3[1] = { 'e' };
static const symbol s_2_4[4] = { 0xC3, 0xAC, 't', 'e' };
static const symbol s_2_5[3] = { 'e', 'c', 'h' };
static const symbol s_2_6[5] = { 'a', 't', 'e', 'c', 'h' };
static const symbol s_2_7[3] = { 'i', 'c', 'h' };
static const symbol s_2_8[4] = { 0xC3, 0xA1, 'c', 'h' };
static const symbol s_2_9[4] = { 0xC3, 0xAD, 'c', 'h' };
static const symbol s_2_10[4] = { 0xC3, 0xBD, 'c', 'h' };
static const symbol s_2_11[1] = { 'i' };
static const symbol s_2_12[2] = { 'm', 'i' };
static const symbol s_2_13[3] = { 'a', 'm', 'i' };
static const symbol s_2_14[3] = { 'e', 'm', 'i' };
static const symbol s_2_15[4] = { 0xC3, 0xAC, 'm', 'i' };
static const symbol s_2_16[4] = { 0xC3, 0xAD, 'm', 'i' };
static const symbol s_2_17[4] = { 0xC3, 0xBD, 'm', 'i' };
static const symbol s_2_18[4] = { 0xC3, 0xAC, 't', 'i' };
static const symbol s_2_19[3] = { 'o', 'v', 'i' };
static const symbol s_2_20[2] = { 'e', 'm' };
static const symbol s_2_21[5] = { 0xC3, 0xAC, 't', 'e', 'm' };
static const symbol s_2_22[3] = { 0xC3, 0xA1, 'm' };
static const symbol s_2_23[3] = { 0xC3, 0xA9, 'm' };
static const symbol s_2_24[3] = { 0xC3, 0xAD, 'm' };
static const symbol s_2_25[5] = { 'a', 't', 0xC3, 0xB9, 'm' };
static const symbol s_2_26[3] = { 0xC3, 0xBD, 'm' };
static const symbol s_2_27[1] = { 'o' };
static const symbol s_2_28[3] = { 'i', 'h', 'o' };
static const symbol s_2_29[4] = { 0xC3, 0xA9, 'h', 'o' };
static const symbol s_2_30[4] = { 0xC3, 0xAD, 'h', 'o' };
static const symbol s_2_31[2] = { 'e', 's' };
static const symbol s_2_32[2] = { 'o', 's' };
static const symbol s_2_33[2] = { 'u', 's' };
static const symbol s_2_34[2] = { 'a', 't' };
static const symbol s_2_35[1] = { 'u' };
static const symbol s_2_36[3] = { 'i', 'm', 'u' };
static const symbol s_2_37[4] = { 0xC3, 0xA9, 'm', 'u' };
static const symbol s_2_38[2] = { 'o', 'u' };
static const symbol s_2_39[1] = { 'y' };
static const symbol s_2_40[3] = { 'a', 't', 'y' };
static const symbol s_2_41[2] = { 0xC3, 0xA1 };
static const symbol s_2_42[2] = { 0xC3, 0xA9 };
static const symbol s_2_43[4] = { 'o', 'v', 0xC3, 0xA9 };
static const symbol s_2_44[2] = { 0xC3, 0xAC };
static const symbol s_2_45[2] = { 0xC3, 0xAD };
static const symbol s_2_46[2] = { 0xC3, 0xB9 };
static const symbol s_2_47[2] = { 0xC3, 0xBD };

static const struct among a_2[48] =
{
{ 1, s_2_0, -1, 1, 0},
{ 3, s_2_1, 0, 1, 0},
{ 3, s_2_2, 0, 1, 0},
{ 1, s_2_3, -1, 2, 0},
{ 4, s_2_4, 3, 2, 0},
{ 3, s_2_5, -1, 2, 0},
{ 5, s_2_6, 5, 1, 0},
{ 3, s_2_7, -1, 2, 0},
{ 4, s_2_8, -1, 1, 0},
{ 4, s_2_9, -1, 2, 0},
{ 4, s_2_10, -1, 1, 0},
{ 1, s_2_11, -1, 2, 0},
{ 2, s_2_12, 11, 1, 0},
{ 3, s_2_13, 12, 1, 0},
{ 3, s_2_14, 12, 2, 0},
{ 4, s_2_15, 12, 2, 0},
{ 4, s_2_16, 12, 2, 0},
{ 4, s_2_17, 12, 1, 0},
{ 4, s_2_18, 11, 2, 0},
{ 3, s_2_19, 11, 1, 0},
{ 2, s_2_20, -1, 3, 0},
{ 5, s_2_21, 20, 1, 0},
{ 3, s_2_22, -1, 1, 0},
{ 3, s_2_23, -1, 2, 0},
{ 3, s_2_24, -1, 2, 0},
{ 5, s_2_25, -1, 1, 0},
{ 3, s_2_26, -1, 1, 0},
{ 1, s_2_27, -1, 1, 0},
{ 3, s_2_28, 27, 2, 0},
{ 4, s_2_29, 27, 2, 0},
{ 4, s_2_30, 27, 2, 0},
{ 2, s_2_31, -1, 2, 0},
{ 2, s_2_32, -1, 1, 0},
{ 2, s_2_33, -1, 1, 0},
{ 2, s_2_34, -1, 1, 0},
{ 1, s_2_35, -1, 1, 0},
{ 3, s_2_36, 35, 2, 0},
{ 4, s_2_37, 35, 2, 0},
{ 2, s_2_38, 35, 1, 0},
{ 1, s_2_39, -1, 1, 0},
{ 3, s_2_40, 39, 1, 0},
{ 2, s_2_41, -1, 1, 0},
{ 2, s_2_42, -1, 1, 0},
{ 4, s_2_43, 42, 1, 0},
{ 2, s_2_44, -1, 2, 0},
{ 2, s_2_45, -1, 2, 0},
{ 2, s_2_46, -1, 1, 0},
{ 2, s_2_47, -1, 1, 0}
};

static const symbol s_3_0[2] = { 'o', 'b' };
static const symbol s_3_1[3] = { 'i', 't', 'b' };
static const symbol s_3_2[2] = { 'e', 'c' };
static const symbol s_3_3[4] = { 'i', 'n', 'e', 'c' };
static const symbol s_3_4[6] = { 'o', 'b', 'i', 'n', 'e', 'c' };
static const symbol s_3_5[4] = { 'o', 'v', 'e', 'c' };
static const symbol s_3_6[2] = { 'i', 'c' };
static const symbol s_3_7[4] = { 'e', 'n', 'i', 'c' };
static const symbol s_3_8[3] = { 'o', 'c', 'h' };
static const symbol s_3_9[5] = { 0xC3, 0xA1, 's', 'e', 'k' };
static const symbol s_3_10[2] = { 'n', 'k' };
static const symbol s_3_11[3] = { 'i', 's', 'k' };
static const symbol s_3_12[5] = { 'o', 'v', 'i', 's', 'k' };
static const symbol s_3_13[2] = { 't', 'k' };
static const symbol s_3_14[2] = { 'v', 'k' };
static const symbol s_3_15[3] = { 0xC3, 0xA8, 'k' };
static const symbol s_3_16[4] = { 'n', 0xC3, 0xAD, 'k' };
static const symbol s_3_17[6] = { 'o', 'v', 'n', 0xC3, 0xAD, 'k' };
static const symbol s_3_18[5] = { 'o', 'v', 0xC3, 0xAD, 'k' };
static const symbol s_3_19[4] = { 'i', 0xC2, 0xB9, 'k' };
static const symbol s_3_20[4] = { 'u', 0xC2, 0xB9, 'k' };
static const symbol s_3_21[2] = { 'd', 'l' };
static const symbol s_3_22[4] = { 'i', 't', 'e', 'l' };
static const symbol s_3_23[2] = { 'u', 'l' };
static const symbol s_3_24[2] = { 'a', 'n' };
static const symbol s_3_25[4] = { 0xC3, 0xA8, 'a', 'n' };
static const symbol s_3_26[2] = { 'e', 'n' };
static const symbol s_3_27[2] = { 'i', 'n' };
static const symbol s_3_28[5] = { 0xC2, 0xB9, 't', 'i', 'n' };
static const symbol s_3_29[4] = { 'o', 'v', 'i', 'n' };
static const symbol s_3_30[4] = { 't', 'e', 'l', 'n' };
static const symbol s_3_31[4] = { 0xC3, 0xA1, 'r', 'n' };
static const symbol s_3_32[4] = { 0xC3, 0xAD, 'r', 'n' };
static const symbol s_3_33[3] = { 'o', 'u', 'n' };
static const symbol s_3_34[4] = { 'l', 'o', 'u', 'n' };
static const symbol s_3_35[3] = { 'o', 'v', 'n' };
static const symbol s_3_36[2] = { 'y', 'n' };
static const symbol s_3_37[3] = { 'k', 'y', 'n' };
static const symbol s_3_38[3] = { 0xC3, 0xA1, 'n' };
static const symbol s_3_39[4] = { 'i', 0xC3, 0xA1, 'n' };
static const symbol s_3_40[3] = { 0xC3, 0xA8, 'n' };
static const symbol s_3_41[3] = { 0xC3, 0xAC, 'n' };
static const symbol s_3_42[3] = { 0xC3, 0xAD, 'n' };
static const symbol s_3_43[2] = { 'a', 's' };
static const symbol s_3_44[2] = { 'i', 't' };
static const symbol s_3_45[2] = { 'o', 't' };
static const symbol s_3_46[3] = { 'i', 's', 't' };
static const symbol s_3_47[3] = { 'o', 's', 't' };
static const symbol s_3_48[4] = { 'n', 'o', 's', 't' };
static const symbol s_3_49[3] = { 'o', 'u', 't' };
static const symbol s_3_50[6] = { 'o', 'v', 'i', 0xC2, 0xB9, 't' };
static const symbol s_3_51[2] = { 'i', 'v' };
static const symbol s_3_52[2] = { 'o', 'v' };
static const symbol s_3_53[2] = { 't', 'v' };
static const symbol s_3_54[3] = { 'c', 't', 'v' };
static const symbol s_3_55[3] = { 's', 't', 'v' };
static const symbol s_3_56[5] = { 'o', 'v', 's', 't', 'v' };
static const symbol s_3_57[4] = { 'o', 'v', 't', 'v' };
static const symbol s_3_58[3] = { 'a', 0xC3, 0xA8 };
static const symbol s_3_59[4] = { 0xC3, 0xA1, 0xC3, 0xA8 };
static const symbol s_3_60[3] = { 'o', 0xC3, 0xB2 };
static const symbol s_3_61[4] = { 0xC3, 0xA1, 0xC3, 0xB8 };
static const symbol s_3_62[5] = { 'k', 0xC3, 0xA1, 0xC3, 0xB8 };
static const symbol s_3_63[7] = { 'i', 'o', 'n', 0xC3, 0xA1, 0xC3, 0xB8 };
static const symbol s_3_64[4] = { 0xC3, 0xA9, 0xC3, 0xB8 };
static const symbol s_3_65[5] = { 'n', 0xC3, 0xA9, 0xC3, 0xB8 };
static const symbol s_3_66[4] = { 0xC3, 0xAD, 0xC3, 0xB8 };
static const symbol s_3_67[4] = { 'o', 'u', 0xC2, 0xB9 };

static const struct among a_3[68] =
{
{ 2, s_3_0, -1, 1, 0},
{ 3, s_3_1, -1, 2, 0},
{ 2, s_3_2, -1, 3, 0},
{ 4, s_3_3, 2, 2, 0},
{ 6, s_3_4, 3, 1, 0},
{ 4, s_3_5, 2, 1, 0},
{ 2, s_3_6, -1, 2, 0},
{ 4, s_3_7, 6, 3, 0},
{ 3, s_3_8, -1, 1, 0},
{ 5, s_3_9, -1, 1, 0},
{ 2, s_3_10, -1, 1, 0},
{ 3, s_3_11, -1, 2, 0},
{ 5, s_3_12, 11, 1, 0},
{ 2, s_3_13, -1, 1, 0},
{ 2, s_3_14, -1, 1, 0},
{ 3, s_3_15, -1, 1, 0},
{ 4, s_3_16, -1, 1, 0},
{ 6, s_3_17, 16, 1, 0},
{ 5, s_3_18, -1, 1, 0},
{ 4, s_3_19, -1, 2, 0},
{ 4, s_3_20, -1, 1, 0},
{ 2, s_3_21, -1, 1, 0},
{ 4, s_3_22, -1, 2, 0},
{ 2, s_3_23, -1, 1, 0},
{ 2, s_3_24, -1, 1, 0},
{ 4, s_3_25, 24, 1, 0},
{ 2, s_3_26, -1, 3, 0},
{ 2, s_3_27, -1, 2, 0},
{ 5, s_3_28, 27, 1, 0},
{ 4, s_3_29, 27, 1, 0},
{ 4, s_3_30, -1, 1, 0},
{ 4, s_3_31, -1, 1, 0},
{ 4, s_3_32, -1, 6, 0},
{ 3, s_3_33, -1, 1, 0},
{ 4, s_3_34, 33, 1, 0},
{ 3, s_3_35, -1, 1, 0},
{ 2, s_3_36, -1, 1, 0},
{ 3, s_3_37, 36, 1, 0},
{ 3, s_3_38, -1, 1, 0},
{ 4, s_3_39, 38, 2, 0},
{ 3, s_3_40, -1, 1, 0},
{ 3, s_3_41, -1, 5, 0},
{ 3, s_3_42, -1, 6, 0},
{ 2, s_3_43, -1, 1, 0},
{ 2, s_3_44, -1, 2, 0},
{ 2, s_3_45, -1, 1, 0},
{ 3, s_3_46, -1, 2, 0},
{ 3, s_3_47, -1, 1, 0},
{ 4, s_3_48, 47, 1, 0},
{ 3, s_3_49, -1, 1, 0},
{ 6, s_3_50, -1, 1, 0},
{ 2, s_3_51, -1, 2, 0},
{ 2, s_3_52, -1, 1, 0},
{ 2, s_3_53, -1, 1, 0},
{ 3, s_3_54, 53, 1, 0},
{ 3, s_3_55, 53, 1, 0},
{ 5, s_3_56, 55, 1, 0},
{ 4, s_3_57, 53, 1, 0},
{ 3, s_3_58, -1, 1, 0},
{ 4, s_3_59, -1, 1, 0},
{ 3, s_3_60, -1, 1, 0},
{ 4, s_3_61, -1, 1, 0},
{ 5, s_3_62, 61, 1, 0},
{ 7, s_3_63, 61, 2, 0},
{ 4, s_3_64, -1, 4, 0},
{ 5, s_3_65, 64, 1, 0},
{ 4, s_3_66, -1, 6, 0},
{ 4, s_3_67, -1, 1, 0}
};

static const symbol s_4_0[1] = { 'c' };
static const symbol s_4_1[1] = { 'k' };
static const symbol s_4_2[1] = { 'l' };
static const symbol s_4_3[1] = { 'n' };
static const symbol s_4_4[1] = { 't' };
static const symbol s_4_5[2] = { 0xC3, 0xA8 };

static const struct among a_4[6] =
{
{ 1, s_4_0, -1, 1, 0},
{ 1, s_4_1, -1, 1, 0},
{ 1, s_4_2, -1, 1, 0},
{ 1, s_4_3, -1, 1, 0},
{ 1, s_4_4, -1, 1, 0},
{ 2, s_4_5, -1, 1, 0}
};

static const symbol s_5_0[3] = { 'i', 's', 'k' };
static const symbol s_5_1[3] = { 0xC3, 0xA1, 'k' };
static const symbol s_5_2[3] = { 'i', 'z', 'n' };
static const symbol s_5_3[4] = { 'a', 'j', 'z', 'n' };

static const struct among a_5[4] =
{
{ 3, s_5_0, -1, 2, 0},
{ 3, s_5_1, -1, 1, 0},
{ 3, s_5_2, -1, 2, 0},
{ 4, s_5_3, -1, 1, 0}
};

static const symbol s_6_0[1] = { 'k' };
static const symbol s_6_1[2] = { 'a', 'k' };
static const symbol s_6_2[2] = { 'e', 'k' };
static const symbol s_6_3[4] = { 'a', 'n', 'e', 'k' };
static const symbol s_6_4[4] = { 'e', 'n', 'e', 'k' };
static const symbol s_6_5[4] = { 'i', 'n', 'e', 'k' };
static const symbol s_6_6[4] = { 'o', 'n', 'e', 'k' };
static const symbol s_6_7[4] = { 'u', 'n', 'e', 'k' };
static const symbol s_6_8[5] = { 0xC3, 0xA1, 'n', 'e', 'k' };
static const symbol s_6_9[5] = { 'a', 0xC3, 0xA8, 'e', 'k' };
static const symbol s_6_10[5] = { 'e', 0xC3, 0xA8, 'e', 'k' };
static const symbol s_6_11[5] = { 'i', 0xC3, 0xA8, 'e', 'k' };
static const symbol s_6_12[5] = { 'o', 0xC3, 0xA8, 'e', 'k' };
static const symbol s_6_13[5] = { 'u', 0xC3, 0xA8, 'e', 'k' };
static const symbol s_6_14[6] = { 0xC3, 0xA1, 0xC3, 0xA8, 'e', 'k' };
static const symbol s_6_15[6] = { 0xC3, 0xA9, 0xC3, 0xA8, 'e', 'k' };
static const symbol s_6_16[6] = { 0xC3, 0xAD, 0xC3, 0xA8, 'e', 'k' };
static const symbol s_6_17[6] = { 'o', 'u', 0xC2, 0xB9, 'e', 'k' };
static const symbol s_6_18[2] = { 'i', 'k' };
static const symbol s_6_19[3] = { 'a', 'n', 'k' };
static const symbol s_6_20[3] = { 'e', 'n', 'k' };
static const symbol s_6_21[3] = { 'i', 'n', 'k' };
static const symbol s_6_22[3] = { 'o', 'n', 'k' };
static const symbol s_6_23[3] = { 'u', 'n', 'k' };
static const symbol s_6_24[4] = { 0xC3, 0xA1, 'n', 'k' };
static const symbol s_6_25[4] = { 0xC3, 0xA9, 'n', 'k' };
static const symbol s_6_26[4] = { 0xC3, 0xAD, 'n', 'k' };
static const symbol s_6_27[2] = { 'o', 'k' };
static const symbol s_6_28[4] = { 0xC3, 0xA1, 't', 'k' };
static const symbol s_6_29[2] = { 'u', 'k' };
static const symbol s_6_30[3] = { 0xC3, 0xA1, 'k' };
static const symbol s_6_31[4] = { 'a', 0xC3, 0xA8, 'k' };
static const symbol s_6_32[4] = { 'e', 0xC3, 0xA8, 'k' };
static const symbol s_6_33[4] = { 'i', 0xC3, 0xA8, 'k' };
static const symbol s_6_34[4] = { 'o', 0xC3, 0xA8, 'k' };
static const symbol s_6_35[4] = { 'u', 0xC3, 0xA8, 'k' };
static const symbol s_6_36[5] = { 0xC3, 0xA1, 0xC3, 0xA8, 'k' };
static const symbol s_6_37[5] = { 0xC3, 0xA9, 0xC3, 0xA8, 'k' };
static const symbol s_6_38[5] = { 0xC3, 0xAD, 0xC3, 0xA8, 'k' };
static const symbol s_6_39[3] = { 0xC3, 0xA9, 'k' };
static const symbol s_6_40[3] = { 0xC3, 0xAD, 'k' };
static const symbol s_6_41[4] = { 'u', 0xC2, 0xB9, 'k' };

static const struct among a_6[42] =
{
{ 1, s_6_0, -1, 1, 0},
{ 2, s_6_1, 0, 7, 0},
{ 2, s_6_2, 0, 2, 0},
{ 4, s_6_3, 2, 1, 0},
{ 4, s_6_4, 2, 2, 0},
{ 4, s_6_5, 2, 4, 0},
{ 4, s_6_6, 2, 1, 0},
{ 4, s_6_7, 2, 1, 0},
{ 5, s_6_8, 2, 1, 0},
{ 5, s_6_9, 2, 1, 0},
{ 5, s_6_10, 2, 2, 0},
{ 5, s_6_11, 2, 4, 0},
{ 5, s_6_12, 2, 1, 0},
{ 5, s_6_13, 2, 1, 0},
{ 6, s_6_14, 2, 1, 0},
{ 6, s_6_15, 2, 3, 0},
{ 6, s_6_16, 2, 5, 0},
{ 6, s_6_17, 2, 1, 0},
{ 2, s_6_18, 0, 4, 0},
{ 3, s_6_19, 0, 1, 0},
{ 3, s_6_20, 0, 1, 0},
{ 3, s_6_21, 0, 1, 0},
{ 3, s_6_22, 0, 1, 0},
{ 3, s_6_23, 0, 1, 0},
{ 4, s_6_24, 0, 1, 0},
{ 4, s_6_25, 0, 1, 0},
{ 4, s_6_26, 0, 1, 0},
{ 2, s_6_27, 0, 8, 0},
{ 4, s_6_28, 0, 1, 0},
{ 2, s_6_29, 0, 9, 0},
{ 3, s_6_30, 0, 6, 0},
{ 4, s_6_31, 0, 1, 0},
{ 4, s_6_32, 0, 1, 0},
{ 4, s_6_33, 0, 1, 0},
{ 4, s_6_34, 0, 1, 0},
{ 4, s_6_35, 0, 1, 0},
{ 5, s_6_36, 0, 1, 0},
{ 5, s_6_37, 0, 1, 0},
{ 5, s_6_38, 0, 1, 0},
{ 3, s_6_39, 0, 3, 0},
{ 3, s_6_40, 0, 5, 0},
{ 4, s_6_41, 0, 1, 0}
};

static const symbol s_7_0[4] = { 'e', 'j', 0xC2, 0xB9 };
static const symbol s_7_1[5] = { 0xC3, 0xAC, 'j', 0xC2, 0xB9 };

static const struct among a_7[2] =
{
{ 4, s_7_0, -1, 2, 0},
{ 5, s_7_1, -1, 1, 0}
};

static const unsigned char g_v[] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 25, 4, 19 };

static const symbol s_0[] = { 'k' };
static const symbol s_1[] = { 'h' };
static const symbol s_2[] = { 'c', 'k' };
static const symbol s_3[] = { 's', 'k' };
static const symbol s_4[] = { 'e' };
static const symbol s_5[] = { 'i' };
static const symbol s_6[] = { 'e' };
static const symbol s_7[] = { 0xC3, 0xA9 };
static const symbol s_8[] = { 0xC3, 0xAC };
static const symbol s_9[] = { 0xC3, 0xAD };
static const symbol s_10[] = { 'i' };
static const symbol s_11[] = { 'e' };
static const symbol s_12[] = { 0xC3, 0xA9 };
static const symbol s_13[] = { 'i' };
static const symbol s_14[] = { 0xC3, 0xAD };
static const symbol s_15[] = { 0xC3, 0xA1 };
static const symbol s_16[] = { 'a' };
static const symbol s_17[] = { 'o' };
static const symbol s_18[] = { 'u' };
static const symbol s_19[] = { 0xC3, 0xAC };
static const symbol s_20[] = { 'e' };

static int r_mark_regions(struct SN_env * z) {
    z->I[1] = z->l;
    z->I[0] = z->l;
    {   int c1 = z->c;
        {   
            int ret = in_grouping_U(z, g_v, 97, 253, 1);
            if (ret < 0) goto lab0;
            z->c += ret;
        }
        z->I[1] = z->c;
        {   
            int ret = in_grouping_U(z, g_v, 97, 253, 1);
            if (ret < 0) goto lab0;
            z->c += ret;
        }
        {   
            int ret = out_grouping_U(z, g_v, 97, 253, 1);
            if (ret < 0) goto lab0;
            z->c += ret;
        }
        z->I[0] = z->c;
    lab0:
        z->c = c1;
    }
    return 1;
}

static int r_RV(struct SN_env * z) {
    if (!(z->I[1] <= z->c)) return 0;
    return 1;
}

static int r_R1(struct SN_env * z) {
    if (!(z->I[0] <= z->c)) return 0;
    return 1;
}

static int r_palatalise(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    among_var = find_among_b(z, a_0, 14);
    if (!(among_var)) return 0;
    z->bra = z->c;
    {   int ret = r_RV(z);
        if (ret <= 0) return ret;
    }
    switch (among_var) {
        case 1:
            {   int ret = slice_from_s(z, 1, s_0);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_from_s(z, 1, s_1);
                if (ret < 0) return ret;
            }
            break;
        case 3:
            {   int ret = slice_from_s(z, 2, s_2);
                if (ret < 0) return ret;
            }
            break;
        case 4:
            {   int ret = slice_from_s(z, 2, s_3);
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_do_possessive(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    if (z->c - 1 <= z->lb || (z->p[z->c - 1] != 110 && z->p[z->c - 1] != 118)) return 0;
    among_var = find_among_b(z, a_1, 3);
    if (!(among_var)) return 0;
    z->bra = z->c;
    {   int ret = r_RV(z);
        if (ret <= 0) return ret;
    }
    switch (among_var) {
        case 1:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m1 = z->l - z->c; (void)m1;
                {   int ret = r_palatalise(z);
                    if (ret == 0) { z->c = z->l - m1; goto lab0; }
                    if (ret < 0) return ret;
                }
            lab0:
                ;
            }
            break;
    }
    return 1;
}

static int r_do_case(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    among_var = find_among_b(z, a_2, 48);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m1 = z->l - z->c; (void)m1;
                {   int ret = r_palatalise(z);
                    if (ret == 0) { z->c = z->l - m1; goto lab0; }
                    if (ret < 0) return ret;
                }
            lab0:
                ;
            }
            break;
        case 3:
            {   int ret = slice_from_s(z, 1, s_4);
                if (ret < 0) return ret;
            }
            {   int m2 = z->l - z->c; (void)m2;
                {   int ret = r_palatalise(z);
                    if (ret == 0) { z->c = z->l - m2; goto lab1; }
                    if (ret < 0) return ret;
                }
            lab1:
                ;
            }
            break;
    }
    return 1;
}

static int r_do_derivational(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    among_var = find_among_b(z, a_3, 68);
    if (!(among_var)) return 0;
    z->bra = z->c;
    {   int ret = r_R1(z);
        if (ret <= 0) return ret;
    }
    switch (among_var) {
        case 1:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_from_s(z, 1, s_5);
                if (ret < 0) return ret;
            }
            {   int ret = r_palatalise(z);
                if (ret <= 0) return ret;
            }
            break;
        case 3:
            {   int ret = slice_from_s(z, 1, s_6);
                if (ret < 0) return ret;
            }
            {   int ret = r_palatalise(z);
                if (ret <= 0) return ret;
            }
            break;
        case 4:
            {   int ret = slice_from_s(z, 2, s_7);
                if (ret < 0) return ret;
            }
            {   int ret = r_palatalise(z);
                if (ret <= 0) return ret;
            }
            break;
        case 5:
            {   int ret = slice_from_s(z, 2, s_8);
                if (ret < 0) return ret;
            }
            {   int ret = r_palatalise(z);
                if (ret <= 0) return ret;
            }
            break;
        case 6:
            {   int ret = slice_from_s(z, 2, s_9);
                if (ret < 0) return ret;
            }
            {   int ret = r_palatalise(z);
                if (ret <= 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_do_deriv_single(struct SN_env * z) {
    z->ket = z->c;
    if (!(find_among_b(z, a_4, 6))) return 0;
    z->bra = z->c;
    {   int ret = slice_del(z);
        if (ret < 0) return ret;
    }
    return 1;
}

static int r_do_augmentative(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    if (z->c - 2 <= z->lb || (z->p[z->c - 1] != 107 && z->p[z->c - 1] != 110)) return 0;
    among_var = find_among_b(z, a_5, 4);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_from_s(z, 1, s_10);
                if (ret < 0) return ret;
            }
            {   int ret = r_palatalise(z);
                if (ret <= 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_do_diminutive(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    if (z->c <= z->lb || z->p[z->c - 1] != 107) return 0;
    among_var = find_among_b(z, a_6, 42);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_from_s(z, 1, s_11);
                if (ret < 0) return ret;
            }
            {   int ret = r_palatalise(z);
                if (ret <= 0) return ret;
            }
            break;
        case 3:
            {   int ret = slice_from_s(z, 2, s_12);
                if (ret < 0) return ret;
            }
            {   int ret = r_palatalise(z);
                if (ret <= 0) return ret;
            }
            break;
        case 4:
            {   int ret = slice_from_s(z, 1, s_13);
                if (ret < 0) return ret;
            }
            {   int ret = r_palatalise(z);
                if (ret <= 0) return ret;
            }
            break;
        case 5:
            {   int ret = slice_from_s(z, 2, s_14);
                if (ret < 0) return ret;
            }
            {   int ret = r_palatalise(z);
                if (ret <= 0) return ret;
            }
            break;
        case 6:
            {   int ret = slice_from_s(z, 2, s_15);
                if (ret < 0) return ret;
            }
            break;
        case 7:
            {   int ret = slice_from_s(z, 1, s_16);
                if (ret < 0) return ret;
            }
            break;
        case 8:
            {   int ret = slice_from_s(z, 1, s_17);
                if (ret < 0) return ret;
            }
            break;
        case 9:
            {   int ret = slice_from_s(z, 1, s_18);
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_do_comparative(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    if (z->c - 3 <= z->lb || z->p[z->c - 1] != 185) return 0;
    among_var = find_among_b(z, a_7, 2);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int ret = slice_from_s(z, 2, s_19);
                if (ret < 0) return ret;
            }
            {   int ret = r_palatalise(z);
                if (ret <= 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_from_s(z, 1, s_20);
                if (ret < 0) return ret;
            }
            {   int ret = r_palatalise(z);
                if (ret <= 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_do_aggressive(struct SN_env * z) {
    {   int m1 = z->l - z->c; (void)m1;
        {   int ret = r_do_comparative(z);
            if (ret < 0) return ret;
        }
        z->c = z->l - m1;
    }
    {   int m2 = z->l - z->c; (void)m2;
        {   int ret = r_do_diminutive(z);
            if (ret < 0) return ret;
        }
        z->c = z->l - m2;
    }
    {   int m3 = z->l - z->c; (void)m3;
        {   int ret = r_do_augmentative(z);
            if (ret < 0) return ret;
        }
        z->c = z->l - m3;
    }
    {   int m4 = z->l - z->c; (void)m4;
        {   int ret = r_do_derivational(z);
            if (ret == 0) goto lab1;
            if (ret < 0) return ret;
        }
        goto lab0;
    lab1:
        z->c = z->l - m4;
        {   int ret = r_do_deriv_single(z);
            if (ret <= 0) return ret;
        }
    }
lab0:
    return 1;
}

extern int czech_UTF_8_stem(struct SN_env * z) {
    
    {   int ret = r_mark_regions(z);
        if (ret < 0) return ret;
    }
    z->lb = z->c; z->c = z->l;

    {   int ret = r_do_case(z);
        if (ret <= 0) return ret;
    }
    {   int ret = r_do_possessive(z);
        if (ret <= 0) return ret;
    }
    {   int ret = r_do_aggressive(z);
        if (ret <= 0) return ret;
    }
    z->c = z->lb;
    return 1;
}

extern struct SN_env * czech_UTF_8_create_env(void) { return SN_create_env(0, 2, 1); }

extern void czech_UTF_8_close_env(struct SN_env * z) { SN_close_env(z, 0); }

